name: Install yq
description: Install the latest yq binary on Ubuntu runners.

runs:
  using: composite
  steps:
    - name: Install yq
      shell: bash
      run: |
        set -e

        # Install yq
        sudo wget -qO /usr/local/bin/yq \
          https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64

        sudo chmod +x /usr/local/bin/yq

        # Verify installation
        yq --version
